### ISSUE TITLE
[BE] Create Admin entity

### ISSUE THREAD

**Issue by DonaldMurillo** [DonaldMurillo/angular-portfolio#5]
- define Admin entity

**Comment by ManuelGCV** [comment]
- [ ]  create Admin model
- [x] Seed predefined Admin
- [x] using .env file for credentials

**Comment by ManuelGCV** [comment]
https://medium.com/the-crowdlinker-chronicle/seeding-databases-using-nestjs-cd6634e8efc5

**Comment by ManuelGCV** [comment]
https://github.com/w3tecch/typeorm-seeding/issues/53
